### ISSUE TITLE
Change default color to gray

### ISSUE THREAD

**Issue by anderscognite** [cognitedata/3d-web-parser#39]
Several of our models in production have nodes without color. @dragly fixed this by assigning them a color, but this makes i.e. Ivar Aasen look funny:

<img width="884" alt="Screenshot 2019-04-09 at 11 14 13" src="https://user-images.githubusercontent.com/34239077/55788504-b9d90280-5ab8-11e9-98f9-ecef6a830bbd.png">

We should set gray as default color or figure out why the previous version of the viewer colors it gray.

**Comment by dragly** [comment]
Let us set it to gray for now and add an issue to set it back to something ugly once we have fixed the underlying issue for all relevant models. I think it is nice that missing color is screaming at you so it does not go unnoticed in later uploads/conversions. We could also have it as a private property to allow users to override it in the worst case.

**Comment by nsunderland-cognite** [comment]
This turned out to be a bug that coloured all instanced meshes with the default colour, and the models are actually fine. Should we check this for other models or just close the issue?

**Comment by anderscognite** [comment]
Yep, I think we're good here.
