### ISSUE TITLE
Add resize function on PrimitiveGroup

### ISSUE THREAD

**Issue by anderscognite** [cognitedata/3d-web-parser#6]
After a group is full / a new one is created, we may want to resize the current group so its capacity is exactly its count to minimize memory usage. This will require some extra copying which hopefully isn't much slower.

**Comment by Verkhovskaya** [comment]
This is unnecessary with the new file parser - I use sector metadata to make sure the groups I create are exactly the right size.

**Comment by anderscognite** [comment]
If we’re keeping protobuf for a long time, then we might have to, but agree on the new parser:)

**Comment by anderscognite** [comment]
I'll close this as protobuf is dying!
